[package]
name = "iris"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
memmap2 = "0.9.5"
rand = "0.8"
thiserror = "1.0.64"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
