# Use Ubuntu 22.04 as the base image
FROM ubuntu:jammy

# install interactive programs (emacs, vim, nano, man, sudo, etc.)
RUN apt-get update && apt-get install -y \
 bc\
 curl\
 dc\
 git\
 git-doc\
 man\
 micro\
 nano\
 psmisc\
 sudo\
 wget\
 screen\
 tmux\
 emacs-nox\
 vim\
 jq \
 file 
