# This file DOES NOT generate new predicates. It uses query predicates 
# previously generated by run.py to create a groundtruth where each query 
# has a different predicate. For each query, we have to run through the 
# top-100 nearest neighbors, and find the 1-NN that matches the predicate

from run import ivecs_read
import numpy as np
import os

data_dir = "siftsmall"
out_dir = "outdir"
gt_name = "siftsmall_groundtruth"
groundtruth_file = os.path.join(data_dir, f"{gt_name}.ivecs")
base_attributes = os.path.join(out_dir, f"siftsmall_base.csv")
query_attributes = os.path.join(out_dir, f"siftsmall_query.csv")

def generate_groundtruth(gt, base_predicates, query_predicates):
    predicate_gt = []
    no_such_index = [] #query vectors where a nearest neighbor wasn't found
    for i in range(len(gt)):
        # for each query vector, checking for the 
        # nearest neighbor matching our predicate
        nearest_neighbors = gt[i]
        predicate = query_predicates[i]  # the filter for this query
        for j in range(100): 
            # for SIFT1M they provide top-100 neighbors in the groundtruth
            pred_index = nearest_neighbors[j]
            # print("NN number", j, base_predicates[pred_index])
            if base_predicates[pred_index] == predicate:
                satisfying_nearest_neighbor = pred_index
                predicate_gt.append(pred_index)
                break
        if satisfying_nearest_neighbor == -1:
            no_such_index.append(i)
    return predicate_gt, no_such_index


def main():
    # Load in original groundtruth ivecs
    print("Reading groundtruth...")
    groundtruth = ivecs_read(groundtruth_file)
    base_predicates = np.loadtxt(base_attributes, delimiter=",", dtype=int)
    query_predicates = np.loadtxt(query_attributes, delimiter=",", dtype=int)
    print(base_predicates[:10])
    print(query_predicates[:10])
    print("Generating groundtruth")
    predicate_gt, no_NN = generate_groundtruth(groundtruth, base_predicates, query_predicates)
    print("No index found for", len(no_NN), "queries")
    print(no_NN[:10])
    
    print("writing down to variable gt csv")
    with open(f"outdir/siftsmall_variable_groundtruth.csv", "w") as f:
        for pred in predicate_gt:
            f.write(f"{pred}\n")

    print("done!")

if __name__ == "__main__":
    main()