build_and_run:
  docker build -t oak .
  docker run \
      -v ./:/oak \
      oak
  # sudo chown -R $(id -u):$(id -g) data/

run:
  docker run \
      -v ./:/oak \
      oak

dev:
  docker run \
      -it \
      -v ./:/oak \
      oak \
      bash

test:
  docker run \
      -it \
      -v ./:/oak \
      oak \
      cargo test -- --test-threads=1 

bench:
  docker run \
      -it \
      -v ./:/oak \
      oak \
      cargo bench --bench oak_benchmark


